### ISSUE TITLE
Allow comma inputs for grades

### ISSUE THREAD

**Issue by Lukas-J** [laurenzfg/notenstreicher#5]
Hi Laurenz,
could you please make it possible for a user to input his grades in the German comma way?
Cheers

**Comment by laurenzfg** [comment]
I currently have no bandwidth to fix this. Drop me a PR, if you want :)

**Comment by laurenzfg** [comment]
Hi Lukas!

once again thx for raising this. I have made a fix which should replace "," with "." upon entry into the tool. Please let me know if this fixes the issue from your end.

The fix is already deployed on the public version.

Closing this for the time being.
