### ISSUE TITLE
Add instructions what to do if a class was ungraded

### ISSUE THREAD

**Issue by Lukas-J** [laurenzfg/notenstreicher#6]
In Covid times, some classes were passed ungraded. Please, provide the user with some info on what to do in that case.

**Comment by laurenzfg** [comment]
I currently have no bandwidth to fix this. Drop me a PR, if you want :)

**Comment by laurenzfg** [comment]
Naah, I just need to add a sentence. But you could have done it, too :1st_place_medal:
